### ISSUE TITLE
All Unnamed buffers use the same filepath - " "

### ISSUE THREAD

**Issue by hallzy** [iago-lito/vim-visualMarks#10]
This only applies if/when pull request #8 has been merged.

multiple unnamed buffers would all use the same dictionary entries. Should try and find a way around this so that we can have multiple unnamed buffers with separate entries.

**Comment by iago-lito** [comment]
Arf, running around for now.. I'll get back to this soon ;) Thank you for #8 by the way !

**Comment by iago-lito** [comment]
Okay, so we should try'da do some kind of unnamed buffer counting. I'll have a look. There must be something identifying the unnamed buffers, even their simple id's in the buffer list..

**Comment by iago-lito** [comment]
Fixed with ff8b1ea! each unnamed buffer is now identified by a special string including its buffer id. (Vim's `bufnr()`). Marking multiple unnamed buffers should work now :)
